### ISSUE TITLE
Doc: unsupported ns timestamp in ELK for log ordering

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-syslog-drain-release#10]
https://github.com/cloudfoundry/cf-syslog-drain-release/blob/develop/README.md#log-ordering mentions 

> Diego uses a nanosecond based timestamp that can be ingested properly by both ELK and Splunk with the instructions linked.

However the referenced [elastisearch date documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/date.html) only mentions milliseconds supports and https://github.com/elastic/elasticsearch/issues/10005 explicitly mentions lack of nanosecond support.

Is this an issue in the documentation, or could the documentation be more precise about ELK nanos support (such as storing the seconds fraction in a distinct ES field than the date) ?

**Comment by thepeterstone** [comment]
Hi @gberche-orange,

Thanks for pointing that out. We've updated the documentation to reflect ELK's millisecond-precision.

**Comment by gberche-orange** [comment]
thanks @thepeterstone
