### ISSUE TITLE
scalablesyslog.adapter.tls.cn seems to be required

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-syslog-drain-release#11]
As of v5.1, the scalablesyslog.adapter.tls.cn BOSH property seems to be required although the description leads one to believe otherwise. (See [adapter spec](https://github.com/cloudfoundry/cf-syslog-drain-release/blob/v5.1/jobs/adapter/spec#L81-L84)) When I leave it out of my deployment I see the following error in the adapter log.

```
2018/02/23 01:11:14 failed to load config from environment: TLS_COMMON_NAME is required but was empty
```

Am I doing something wrong or is the description in the spec out-of-date?

**Comment by bradylove** [comment]
@forbushbl Thank you for pointing that out. For some reason the description was changed and a default was added with an empty string, however that property is required. I have updated the adapter spec to reflect that.

**Comment by forbushbl** [comment]
@bradylove Awesome, thanks!
