### ISSUE TITLE
Adapter and Scheduler not sending logs to syslog

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-syslog-drain-release#12]
It appears that adapter and scheduler are not sending their logs to syslog via `logger`. I know that blackbox is the way of the future but it would be nice to get these logs via `logger` in the interim.

[Doppler (working)](https://github.com/cloudfoundry/loggregator-release/blob/v101.6/jobs/doppler/templates/doppler_ctl.erb#L38)
[Adapter](https://github.com/cloudfoundry/cf-syslog-drain-release/blob/v5.1/jobs/adapter/templates/ctl.erb#L26-L27)
[Scheduler](https://github.com/cloudfoundry/cf-syslog-drain-release/blob/v5.1/jobs/scheduler/templates/ctl.erb#L23-L24)

Also see: https://github.com/cloudfoundry/loggregator-release/issues/363

**Comment by hev** [comment]
@forbushbl this is not handled within our release so I am going to close this issue. As you mentioned this should be resolved with updates to the syslog-release.
