### ISSUE TITLE
Look into removing potentially noisy log messages from adapter

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-syslog-drain-release#16]
We recently deployed the latest cf-syslog-drain-release and we're loving the reduced logging.  However, we're still seeing some log messages in the adapter that look like they might be problems or noise.

```
failed to open stream for binding 8c3cf578-7463-490d-8d85-f806fc4ee9cf: rpc error: code = Canceled desc = grpc: the client connection is closing
Failed to connect to loggregator API: context deadline exceeded
```

Posted the above on slack and @apoydence responded that he believed it was just noise: https://cloudfoundry.slack.com/archives/C02HCCXV5/p1526579911000361

**Comment by bradylove** [comment]
These log lines have been removed in [bae849896779be7edd37b8a5f978556a129d4797](https://github.com/cloudfoundry/scalable-syslog/commit/bae849896779be7edd37b8a5f978556a129d4797)

**Comment by cwb124** [comment]
Has it been confirmed that the error below is in fact noise or is it a real error that causes problems?

`Failed to connect to loggregator API: context deadline exceeded`

**Comment by MasslessParticle** [comment]
In general, these log lines do not indicate an issue.
