### ISSUE TITLE
After upgrading to release v7.1 - something is shutting down adapter

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry/cf-syslog-drain-release#18]
Right after upgrading to v7.1 from v6.5 the log chatter stopped but I see the following log messages that tells me the adapter stopped but I can't seem to find why.  A `monit summary` shows the adapter is running but the adapter.log shows

2018/09/20 13:22:36 Draining connections...
2018/09/20 13:22:36 Done draining connections.
2018/09/20 13:22:36 Shutting down adapter server

**Comment by jtuchscherer** [comment]
Link to Slack thread: https://cloudfoundry.slack.com/archives/C02HCCXV5/p1537472681000100

**Comment by poy** [comment]
@cwb124 I suspect this is left over from our transition to [bpm](https://bosh.io/docs/bpm/bpm/). 

bpm creates two log files for each process (one for `stdout` and the other for `stderr`) but does not cleanup existing files. Therefore, you see the old log file (`adapter.log`) with its final shutdown message, and all future logs going to `adapter.stderr.log`.
