### ISSUE TITLE
The gosec tool found 2 high severity issues in cf-syslog-drain-release-8.0

### ISSUE THREAD

**Issue by Wayne-H-Ha** [cloudfoundry/cf-syslog-drain-release#20]
Not sure if it is OK that the gosec tool found the following 2 high severity issues in cf-syslog-drain-release-8.0:

```
{
 "severity": "HIGH",
 "confidence": "HIGH",
 "rule_id": "G402",
 "details": "TLS InsecureSkipVerify set true.",
 "file": "/tmp/composer/src/workdir/packages/code.cloudfoundry.org/scalable-syslog/adapter/internal/egress/tls.go",
 "code": "InsecureSkipVerify: skipCertVerify",
 "line": "36"
},
{
 "severity": "HIGH",
 "confidence": "MEDIUM",
 "rule_id": "G404",
 "details": "Use of weak random number generator (math/rand instead of crypto/rand)",
 "file": "/tmp/composer/src/workdir/packages/code.cloudfoundry.org/scalable-syslog/adapter/internal/ingress/ip_balancer.go",
 "code": "rand.Int()",
 "line": "57"
},
```

**Comment by bradylove** [comment]
Hi @Wayne-H-Ha,

Thank you for opening this issue. To address the first issue with `InsecureSkipVerify`, that value comes from the config which defaults to `false` (https://github.com/cloudfoundry/scalable-syslog/blob/58c4fd7c342ddecc836fff577682bcad56026a9f/adapter/app/config.go#L50) so I do not believe that is an issue.

To address the second issue, that random number generator is used to decide which RLP (Reverse Log Proxy) to connect to and does not need to be securely random.

I am going to go ahead and close out this issue, if you have any further concerns please feel free to re-open.
