### ISSUE TITLE
Some logs are lost every 10 minutes

### ISSUE THREAD

**Issue by giner** [cloudfoundry/cf-syslog-drain-release#21]
Syslog drain gets some logs missing every 10 minutes. Here is what we know at the moment:
- all logs reach traffic controller successfully (we get all logs from firehose without drops)
- some logs don't get out of adapter (tested with tcpdump)
- drops happen every 10 minutes

We tested the following versions of cf-syslog-drain-release:
- 4
- 5.1
- 6.5
- 8.1 (cf-deployment v6.8.0)

Here is how to reproduce:
1. Configure syslog drain (we use rsyslog for testing)
```
cf cups syslog -l syslog://10.10.10.10:10514
```
2. Push a script generating sequential numbers
```
mkdir /tmp/test
cd /tmp/test
touch .test
cf push logtest --no-start --no-route -u process -b https://github.com/cloudfoundry/binary-buildpack -c 'bash -c "x=1; while true; do sleep 0.1; echo unique-line-to-grep \$x; ((x++)); done"'
```
3. Bind the service and start the app
```
cf bind-service logtest syslog
cf start testlog
```
4. Run for 30-40 minutes, stop the app and wait for a few more seconds for buffers to be flushed
```
cf stop testlog
```
5. Check logs on rsyslog server
```
s=unique-line-to-grep; f=/tmp/$s; grep $s /var/log/syslog | sort > $f; tail -n1 $f; wc -l $f
```
The result:
```
Dec 29 10:24:15 test.test.logtest 5896cacb-5207-4c06-80e7-aeb4a8681689[[APP/PROC/WEB/0]] unique-line-to-grep 34720
34706 /tmp/unique-line-to-grep  # number of lines written to rsyslog with unique line
```

It seems that we get logs lost when adapter reconnects to rlp here https://github.com/cloudfoundry/scalable-syslog/blob/6288c1f60cca8f7838eea60fea27b8ed4d84f629/adapter/internal/ingress/client_manager.go#L103.

**Comment by bradylove** [comment]
Hi @giner,

This is a known issue. The adapter itself will drain any messages it has in its buffer during the reconnect however some messages are lost in Doppler and the Reverse Log Proxy.

We are currently in the process of changing the architecture of the syslog system and the new system will resolve this issue and will overall have better reliability.

/cc @jtuchscherer

**Comment by giner** [comment]
Hi @bradylove,

> This is a known issue

Do you mean there is a story for this? I didn't manage to find anything.

> The adapter itself will drain any messages it has in its buffer during the reconnect however some messages are lost in Doppler and the Reverse Log Proxy.

We don't have logs lost in Doppler, otherwise we would have them missing form firehose.

> We are currently in the process of changing the architecture of the syslog system and the new system will resolve this issue and will overall have better reliability.

I understand this though log aggregation is one of the core features of Cloud Foundry which make users love and keep using it so I think this as a serious issue. These drops are not occasional, they happen every 10 minutes and the more logs you send to the drain, the more are lost.

Back to the technical details, why would adapter recreate a connection every 10 minutes? If there is a good reason to do so adapter should be able to drain logs gracefully. ~~If I remember correctly the drops don't happen when adapter is stopped with SIGTERM~~ (I'm planning to do the test again to confirm this).

**Update**
Restarting `adapter` by sending SIGTERM doesn't cause log loss. Have just tested this case.
**Update2**
Restarting `adapter` by sending SIGTERM does cause some logs loss when throughput is high. E.g. when sending 50 lines per second restart by SIGTERM caused 4 lines to be lost.

**Comment by bradylove** [comment]
Hi @giner,

The log loss I am referring to is envelopes that are inflight in the RLP or inflight from Doppler to RLP when the connection is rolled. When the adapter closes the connection, anything that is inflight in the RLP will be lost. The adapter streams are separate from the firehose stream and these lost logs do not show up in a metric anywhere.

The reason we are rolling the connection every 10 minutes is to load balance across the RLP's, it is not the greatest approach to load balancing.

@jtuchscherer can you weigh in on next steps here?

**Comment by giner** [comment]
Hi @bradylove, how about making the TTL configurable as a work around?

**Comment by bradylove** [comment]
@giner I am going to have to defer to @MasslessParticle or @jtuchscherer as I am no longer on the Loggregator team.

**Comment by jtuchscherer** [comment]
@giner Making the TTL configurable would be very reasonable. Would you be interested in PR'ing this?
If not, I can see where we prioritize this.

**Comment by kitemongerer** [comment]
Looks like the PR solved this. I'm going to close the issue let us know if it needs to be reopened for any reason

**Comment by b10s** [comment]
@kitemongerer thank you for checking the issue.
The PR gives us opportunity to change the time duration during which will be no resync and therefore no log lost.

However after timeout resync will happen with log lost.

So strictly speaking issues still there.


p.s.: I'm not sure how to choose proper timeout (what should I measure and check before choosing this value)

**Comment by kitemongerer** [comment]
@b10s We aren't really sure how to choose a proper timeout either. I think a possible approach is to switch to using the syslog-agent instead. It's deployed on each VM and only handles the logs from that VM meaning it doesn't connect to RLP and will circumvent this issue entirely.

Ops file to include syslog agent: https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/add-syslog-agent.yml

You will also want to remove the adapter and scheduler jobs to avoid duplicate logs.

**Comment by pianohacker** [comment]
We don't believe there's a perfect way to fix this particular issue in this version of the CF syslog architecture. Our recommendation for those running into this issue is to switch to agent-based syslog, using the loggregator-agent release and this ops file: https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/add-syslog-agent.yml
