### ISSUE TITLE
Drains Failing for longer time when recreating Adapter VMs on Dynamic Networks

### ISSUE THREAD

**Issue by katter** [cloudfoundry/cf-syslog-drain-release#22]
**What's happening:** When redeploying e.g. CF with a recreation of VMs (e.g. Stemcell Bump) App log Drains (e.g. CF CUPS created) will not work from the last VM being recreated holding the Adapter Job, to the first VM holding a Scheduler job having been successfully being recreated. 
There can be a long time in between however, depending on the size of your deployment. Hours in our case.

**Workaround:** Manually `monit restart scheduler` when Adapter VMs got recreated.

**Important:** We are aware that we can lose logs, particularly during redeployments. This is not a big deal. In this case, we are essentially loosing logs during most of the redeployment time which is in a region of hours.

**Steps to reproduce:** Deploy CF with a *dynamic* network in GCP, CF CUPS, bind an app, eg. "test", follow the app logs, then bump the stem cell of your CF deployment and redeploy.

**Let me share how I reproduce it:**
Given the following **before** kicking off a redeploy:
`adapter/1439cecc-ce91-45f7-836a-a75482492e34                 running        z1  10.80.200.73`
`adapter/3baa995a-6344-45d0-9d13-f0012a5b5ff7                 running        z2  10.80.200.127`
`scheduler/2e185d26-e3bc-492d-ac4f-fa7fbd9ad2c2               running        z2  10.80.200.91`
`scheduler/5c121928-e2d2-4244-ae5d-440c0d213ab6               running        z1  10.80.200.86`

Adapters are in the config of scheduler:
`ADAPTER_ADDRS: "1439cecc-ce91-45f7-836a-a75482492e34.adapter.default.cf-test.bosh,3baa995a-6344-45d0-9d13-f0012a5b5ff7.adapter.default.cf-test.bosh"`
and resolving DNS shows me:
`1439cecc-ce91-45f7-836a-a75482492e34.adapter.default.cf-test.bosh has address 10.80.200.73`
and the outgoing connections of scheduler show as:
`tcp        0      0 10.80.200.91:59180      10.80.200.127:4443      ESTABLISHED 5703/scheduler`
`tcp        0      0 10.80.200.91:50434      10.80.200.73:4443       ESTABLISHED 5703/scheduler`

Curling health on the adapters gives me:
`{"drainCount":1}`

Curling health on the adapters gives me:
`{"adapterCount":2,"blacklistedOrInvalidUrlCount":0,"drainCount":1}`

All nice, everything working. Now let's bump the stemcell and stop the deploy as soon as the adapters are through. Now we have:
`adapter/1439cecc-ce91-45f7-836a-a75482492e34                 running        z1  10.80.200.4`
`adapter/3baa995a-6344-45d0-9d13-f0012a5b5ff7                 running        z2  10.80.200.3`
`scheduler/2e185d26-e3bc-492d-ac4f-fa7fbd9ad2c2               running        z2  10.80.200.91`
`scheduler/5c121928-e2d2-4244-ae5d-440c0d213ab6               running        z1  10.80.200.86`
IaaS handed out new IPs for our Adapter VMs (Dynamic Network).

That leads to the **healthcheck on Adapter** showing:
`{}`

**Healthcheck on Scheduler** showing:
`{"adapterCount":2,"blacklistedOrInvalidUrlCount":0,"drainCount":1}`

with **DNS** on the **Scheduler VM** resolving e.g.:
`1439cecc-ce91-45f7-836a-a75482492e34.adapter.default.cf-test.bosh has address 10.80.200.4`

**BUT still:**
`tcp        0      1 10.80.200.91:43934      10.80.200.127:4443      SYN_SENT    5703/scheduler`
`tcp        0      1 10.80.200.91:35318      10.80.200.73:4443       SYN_SENT    5703/scheduler`

So ofc, scheduler only resolves the IP of the configured Adapters once the task is started. If nothing happens that restarts the scheduler job, it will keep those connections open forever.

In HAProxy, if you don't configure the DNS hold time correctly similar happens, so some similar feature in scheduler would be handy.

**Comment by akshaymankar** [comment]
With SCF/Eirini the network is always dynamic (on K8s). We don't have a production problem, but Eirini team's CATS pipelines keep flaking due to this :(

**Comment by pianohacker** [comment]
With the recent release of cf-deployment v13 that replaces this release with the syslog agents from loggregator-agent-release, we are no longer prioritizing bugfixes on this release. Closing this issue.
