### ISSUE TITLE
TLS v1.2 not pinned in v10.2.5 

### ISSUE THREAD

**Issue by brunograz** [cloudfoundry/cf-syslog-drain-release#29]
The release notes of 10.2.5 mention that TLS is pinned to v1.2 but that does not seem to be the case as the commit was not included in the release and is currently only in the develop branch (8.2.4 also has the commit).

Please disregard this issue in case I overlooked it but the release notes should be updated to reflect the actual state of the release.

**Comment by Benjamintf1** [comment]
With the recent release of cf-deployment v13 that replaces this release with the syslog agents from loggregator-agent-release, we are no longer prioritizing bugfixes on this release. Closing this issue.
