### ISSUE TITLE
When a cf task created via v3 has a space in the name, syslog fails to send

### ISSUE THREAD

**Issue by Benjamintf1** [cloudfoundry/cf-syslog-drain-release#9]
When we create a cf task with a name that has a space, such as 

```
cf curl /v3/apps/{app-guid}/tasks -d '{ "command": "echo 1", "name": "a space" }'
```

When it is bound to syslog drain, we experience the back off errors like so

```
ERR Syslog Drain: Error when writing. Backing off for 1.003ms.
```

We tested this on pws, and used papertrail for our syslog drain. The errors do not appear if the task name has no space. We suspect this has to do with some un-escaped space in a url or payload to syslog.

**Comment by johannaratliff** [comment]
@Benjamintf1 It looks like when we build the url binding, we pass through whatever [name](
https://github.com/cloudfoundry/scalable-syslog/blob/master/adapter/internal/egress/url_binding.go#L34) is given to us through routing. It doesn't look like there's anywhere in our release that would be responsible for encoding spaces to `%20`.

**Comment by hev** [comment]
After further team discussion we determined that we should gracefully hand the bad name by encoding as described above. This should also be addressed in CAPI but I am going going to re-open the issue and associated story.

**Comment by bradylove** [comment]
This has been fixed in https://github.com/cloudfoundry/scalable-syslog/commit/dcfe6f76350a824436c9f6a6c8b55f1c4796649e
